package beans;
// Generated Feb 12, 2019 11:30:09 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Biografija generated by hbm2java
 */
@Entity
@Table(name="biografija"
    ,catalog="job_fair"
)
public class Biografija  implements java.io.Serializable {


     private int idstudent;
     private Student student;
     private String ime;
     private String prezime;
     private String adresa;
     private int postanskiBr;
     private String drzava;
     private String grad;
     private String communicationSkills;
     private String organisationalSkills;
     private String jobrelatedSkills;
     private String telefon;
     private Set<Obrazovanje> obrazovanjes = new HashSet<Obrazovanje>(0);
     private Set<Zaposlenje> zaposlenjes = new HashSet<Zaposlenje>(0);
     private Set<Jezici> jezicis = new HashSet<Jezici>(0);
     private Set<Prijavanakonkurs> prijavanakonkurses = new HashSet<Prijavanakonkurs>(0);
     private Set<WebSites> webSiteses = new HashSet<WebSites>(0);

    public Biografija() {
    }

	
    public Biografija(Student student, String ime, String prezime, String adresa, int postanskiBr, String drzava, String grad, String communicationSkills, String organisationalSkills, String jobrelatedSkills, String telefon) {
        this.student = student;
        this.ime = ime;
        this.prezime = prezime;
        this.adresa = adresa;
        this.postanskiBr = postanskiBr;
        this.drzava = drzava;
        this.grad = grad;
        this.communicationSkills = communicationSkills;
        this.organisationalSkills = organisationalSkills;
        this.jobrelatedSkills = jobrelatedSkills;
        this.telefon = telefon;
    }
    public Biografija(Student student, String ime, String prezime, String adresa, int postanskiBr, String drzava, String grad, String communicationSkills, String organisationalSkills, String jobrelatedSkills, String telefon, Set<Obrazovanje> obrazovanjes, Set<Zaposlenje> zaposlenjes, Set<Jezici> jezicis, Set<Prijavanakonkurs> prijavanakonkurses, Set<WebSites> webSiteses) {
       this.student = student;
       this.ime = ime;
       this.prezime = prezime;
       this.adresa = adresa;
       this.postanskiBr = postanskiBr;
       this.drzava = drzava;
       this.grad = grad;
       this.communicationSkills = communicationSkills;
       this.organisationalSkills = organisationalSkills;
       this.jobrelatedSkills = jobrelatedSkills;
       this.telefon = telefon;
       this.obrazovanjes = obrazovanjes;
       this.zaposlenjes = zaposlenjes;
       this.jezicis = jezicis;
       this.prijavanakonkurses = prijavanakonkurses;
       this.webSiteses = webSiteses;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="student"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idstudent", unique=true, nullable=false)
    public int getIdstudent() {
        return this.idstudent;
    }
    
    public void setIdstudent(int idstudent) {
        this.idstudent = idstudent;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="ime", nullable=false, length=45)
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }

    
    @Column(name="prezime", nullable=false, length=45)
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }

    
    @Column(name="adresa", nullable=false, length=45)
    public String getAdresa() {
        return this.adresa;
    }
    
    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }

    
    @Column(name="postanski_br", nullable=false)
    public int getPostanskiBr() {
        return this.postanskiBr;
    }
    
    public void setPostanskiBr(int postanskiBr) {
        this.postanskiBr = postanskiBr;
    }

    
    @Column(name="drzava", nullable=false, length=45)
    public String getDrzava() {
        return this.drzava;
    }
    
    public void setDrzava(String drzava) {
        this.drzava = drzava;
    }

    
    @Column(name="grad", nullable=false, length=45)
    public String getGrad() {
        return this.grad;
    }
    
    public void setGrad(String grad) {
        this.grad = grad;
    }

    
    @Column(name="communication_skills", nullable=false, length=200)
    public String getCommunicationSkills() {
        return this.communicationSkills;
    }
    
    public void setCommunicationSkills(String communicationSkills) {
        this.communicationSkills = communicationSkills;
    }

    
    @Column(name="organisational_skills", nullable=false, length=200)
    public String getOrganisationalSkills() {
        return this.organisationalSkills;
    }
    
    public void setOrganisationalSkills(String organisationalSkills) {
        this.organisationalSkills = organisationalSkills;
    }

    
    @Column(name="jobrelated_skills", nullable=false, length=200)
    public String getJobrelatedSkills() {
        return this.jobrelatedSkills;
    }
    
    public void setJobrelatedSkills(String jobrelatedSkills) {
        this.jobrelatedSkills = jobrelatedSkills;
    }

    
    @Column(name="telefon", nullable=false, length=45)
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="biografija")
    public Set<Obrazovanje> getObrazovanjes() {
        return this.obrazovanjes;
    }
    
    public void setObrazovanjes(Set<Obrazovanje> obrazovanjes) {
        this.obrazovanjes = obrazovanjes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="biografija")
    public Set<Zaposlenje> getZaposlenjes() {
        return this.zaposlenjes;
    }
    
    public void setZaposlenjes(Set<Zaposlenje> zaposlenjes) {
        this.zaposlenjes = zaposlenjes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="biografija")
    public Set<Jezici> getJezicis() {
        return this.jezicis;
    }
    
    public void setJezicis(Set<Jezici> jezicis) {
        this.jezicis = jezicis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="biografija")
    public Set<Prijavanakonkurs> getPrijavanakonkurses() {
        return this.prijavanakonkurses;
    }
    
    public void setPrijavanakonkurses(Set<Prijavanakonkurs> prijavanakonkurses) {
        this.prijavanakonkurses = prijavanakonkurses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="biografija")
    public Set<WebSites> getWebSiteses() {
        return this.webSiteses;
    }
    
    public void setWebSiteses(Set<WebSites> webSiteses) {
        this.webSiteses = webSiteses;
    }




}


