package beans;
// Generated Feb 12, 2019 11:30:09 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatumZaCv generated by hbm2java
 */
@Entity
@Table(name="datumZaCv"
    ,catalog="job_fair"
)
public class DatumZaCv  implements java.io.Serializable {


     private int id;
     private Date datumPocetak;
     private Date datumKraj;

    public DatumZaCv() {
    }

    public DatumZaCv(int id, Date datumPocetak, Date datumKraj) {
       this.id = id;
       this.datumPocetak = datumPocetak;
       this.datumKraj = datumKraj;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datumPocetak", nullable=false, length=10)
    public Date getDatumPocetak() {
        return this.datumPocetak;
    }
    
    public void setDatumPocetak(Date datumPocetak) {
        this.datumPocetak = datumPocetak;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datumKraj", nullable=false, length=10)
    public Date getDatumKraj() {
        return this.datumKraj;
    }
    
    public void setDatumKraj(Date datumKraj) {
        this.datumKraj = datumKraj;
    }




}


