package beans;
// Generated Feb 12, 2019 11:30:09 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Jezici generated by hbm2java
 */
@Entity
@Table(name="jezici"
    ,catalog="job_fair"
)
public class Jezici  implements java.io.Serializable {


     private Integer idjezici;
     private Biografija biografija;
     private String jezik;
     private String tip;

    public Jezici() {
    }

    public Jezici(Biografija biografija, String jezik, String tip) {
       this.biografija = biografija;
       this.jezik = jezik;
       this.tip = tip;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idjezici", unique=true, nullable=false)
    public Integer getIdjezici() {
        return this.idjezici;
    }
    
    public void setIdjezici(Integer idjezici) {
        this.idjezici = idjezici;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCV", nullable=false)
    public Biografija getBiografija() {
        return this.biografija;
    }
    
    public void setBiografija(Biografija biografija) {
        this.biografija = biografija;
    }

    
    @Column(name="jezik", nullable=false, length=45)
    public String getJezik() {
        return this.jezik;
    }
    
    public void setJezik(String jezik) {
        this.jezik = jezik;
    }

    
    @Column(name="tip", nullable=false, length=45)
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }




}


