package beans;
// Generated Feb 10, 2019 3:24:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Konkurs generated by hbm2java
 */
@Entity
@Table(name="konkurs"
    ,catalog="job_fair"
)
public class Konkurs  implements java.io.Serializable {


     private Integer id;
     private Kompanija kompanija;
     private String pozicija;
     private String tipKonkurs;
     private Date rok;
     private String opis;

    public Konkurs() {
    }

    public Konkurs(Kompanija kompanija, String pozicija, String tipKonkurs, Date rok, String opis) {
       this.kompanija = kompanija;
       this.pozicija = pozicija;
       this.tipKonkurs = tipKonkurs;
       this.rok = rok;
       this.opis = opis;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idkonkurs", nullable=false)
    public Kompanija getKompanija() {
        return this.kompanija;
    }
    
    public void setKompanija(Kompanija kompanija) {
        this.kompanija = kompanija;
    }

    
    @Column(name="pozicija", nullable=false, length=45)
    public String getPozicija() {
        return this.pozicija;
    }
    
    public void setPozicija(String pozicija) {
        this.pozicija = pozicija;
    }

    
    @Column(name="tipKonkurs", nullable=false, length=45)
    public String getTipKonkurs() {
        return this.tipKonkurs;
    }
    
    public void setTipKonkurs(String tipKonkurs) {
        this.tipKonkurs = tipKonkurs;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="rok", nullable=false, length=10)
    public Date getRok() {
        return this.rok;
    }
    
    public void setRok(Date rok) {
        this.rok = rok;
    }

    
    @Column(name="opis", nullable=false, length=100)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }




}


