package beans;
// Generated Feb 3, 2019 8:02:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Konkurs generated by hbm2java
 */
@Entity
@Table(name="konkurs"
    ,catalog="job_fair"
)
public class Konkurs  implements java.io.Serializable {


     private Integer id;
     private String tipKonkursa;
     private String pozicija;
     private Date rok;
     private String opis;

    public Konkurs() {
    }

    public Konkurs(String tipKonkursa, String pozicija, Date rok, String opis) {
       this.tipKonkursa = tipKonkursa;
       this.pozicija = pozicija;
       this.rok = rok;
       this.opis = opis;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="tip_konkursa", nullable=false, length=45)
    public String getTipKonkursa() {
        return this.tipKonkursa;
    }
    
    public void setTipKonkursa(String tipKonkursa) {
        this.tipKonkursa = tipKonkursa;
    }

    
    @Column(name="pozicija", nullable=false, length=45)
    public String getPozicija() {
        return this.pozicija;
    }
    
    public void setPozicija(String pozicija) {
        this.pozicija = pozicija;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="rok", nullable=false, length=19)
    public Date getRok() {
        return this.rok;
    }
    
    public void setRok(Date rok) {
        this.rok = rok;
    }

    
    @Column(name="opis", nullable=false, length=100)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }




}


