package beans;
// Generated Feb 10, 2019 3:24:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Prijavanasajam generated by hbm2java
 */
@Entity
@Table(name="prijavanasajam"
    ,catalog="job_fair"
)
public class Prijavanasajam  implements java.io.Serializable {


     private int idkompanije;
     private Kompanija kompanija;
     private String tipprijave;
     private String status;

    public Prijavanasajam() {
    }

    public Prijavanasajam(Kompanija kompanija, String tipprijave, String status) {
       this.kompanija = kompanija;
       this.tipprijave = tipprijave;
       this.status = status;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="kompanija"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idkompanije", unique=true, nullable=false)
    public int getIdkompanije() {
        return this.idkompanije;
    }
    
    public void setIdkompanije(int idkompanije) {
        this.idkompanije = idkompanije;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Kompanija getKompanija() {
        return this.kompanija;
    }
    
    public void setKompanija(Kompanija kompanija) {
        this.kompanija = kompanija;
    }

    
    @Column(name="tipprijave", nullable=false, length=45)
    public String getTipprijave() {
        return this.tipprijave;
    }
    
    public void setTipprijave(String tipprijave) {
        this.tipprijave = tipprijave;
    }

    
    @Column(name="status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


