package beans;
// Generated Feb 12, 2019 2:08:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Prijavanakonkurs generated by hbm2java
 */
@Entity
@Table(name="prijavanakonkurs"
    ,catalog="job_fair"
)
public class Prijavanakonkurs  implements java.io.Serializable {


     private Integer id;
     private Biografija biografija;
     private Konkurs konkurs;
     private String status;
     private String coverletter;

    public Prijavanakonkurs() {
    }

    public Prijavanakonkurs(Biografija biografija, Konkurs konkurs, String status, String coverletter) {
       this.biografija = biografija;
       this.konkurs = konkurs;
       this.status = status;
       this.coverletter = coverletter;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcv", nullable=false)
    public Biografija getBiografija() {
        return this.biografija;
    }
    
    public void setBiografija(Biografija biografija) {
        this.biografija = biografija;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idkonkurs", nullable=false)
    public Konkurs getKonkurs() {
        return this.konkurs;
    }
    
    public void setKonkurs(Konkurs konkurs) {
        this.konkurs = konkurs;
    }

    
    @Column(name="status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="coverletter", nullable=false, length=45)
    public String getCoverletter() {
        return this.coverletter;
    }
    
    public void setCoverletter(String coverletter) {
        this.coverletter = coverletter;
    }




}


