package beans;
// Generated Feb 12, 2019 2:08:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sajam generated by hbm2java
 */
@Entity
@Table(name="sajam"
    ,catalog="job_fair"
)
public class Sajam  implements java.io.Serializable {


     private int idsajam;
     private String imeSajma;
     private String imesale;
     private Date datumkraj;
     private Date datumpocetak;
     private String jedanaest;
     private String dvanaest;
     private String trinaest;
     private String cetrnaest;
     private String petnaest;
     private String sajamcol;

    public Sajam() {
    }

	
    public Sajam(int idsajam) {
        this.idsajam = idsajam;
    }
    public Sajam(int idsajam, String imeSajma, String imesale, Date datumkraj, Date datumpocetak, String jedanaest, String dvanaest, String trinaest, String cetrnaest, String petnaest, String sajamcol) {
       this.idsajam = idsajam;
       this.imeSajma = imeSajma;
       this.imesale = imesale;
       this.datumkraj = datumkraj;
       this.datumpocetak = datumpocetak;
       this.jedanaest = jedanaest;
       this.dvanaest = dvanaest;
       this.trinaest = trinaest;
       this.cetrnaest = cetrnaest;
       this.petnaest = petnaest;
       this.sajamcol = sajamcol;
    }
   
     @Id 

    
    @Column(name="idsajam", unique=true, nullable=false)
    public int getIdsajam() {
        return this.idsajam;
    }
    
    public void setIdsajam(int idsajam) {
        this.idsajam = idsajam;
    }

    
    @Column(name="imeSajma", length=45)
    public String getImeSajma() {
        return this.imeSajma;
    }
    
    public void setImeSajma(String imeSajma) {
        this.imeSajma = imeSajma;
    }

    
    @Column(name="imesale", length=45)
    public String getImesale() {
        return this.imesale;
    }
    
    public void setImesale(String imesale) {
        this.imesale = imesale;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datumkraj", length=10)
    public Date getDatumkraj() {
        return this.datumkraj;
    }
    
    public void setDatumkraj(Date datumkraj) {
        this.datumkraj = datumkraj;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datumpocetak", length=10)
    public Date getDatumpocetak() {
        return this.datumpocetak;
    }
    
    public void setDatumpocetak(Date datumpocetak) {
        this.datumpocetak = datumpocetak;
    }

    
    @Column(name="jedanaest", length=45)
    public String getJedanaest() {
        return this.jedanaest;
    }
    
    public void setJedanaest(String jedanaest) {
        this.jedanaest = jedanaest;
    }

    
    @Column(name="dvanaest", length=45)
    public String getDvanaest() {
        return this.dvanaest;
    }
    
    public void setDvanaest(String dvanaest) {
        this.dvanaest = dvanaest;
    }

    
    @Column(name="trinaest", length=45)
    public String getTrinaest() {
        return this.trinaest;
    }
    
    public void setTrinaest(String trinaest) {
        this.trinaest = trinaest;
    }

    
    @Column(name="cetrnaest", length=45)
    public String getCetrnaest() {
        return this.cetrnaest;
    }
    
    public void setCetrnaest(String cetrnaest) {
        this.cetrnaest = cetrnaest;
    }

    
    @Column(name="petnaest", length=45)
    public String getPetnaest() {
        return this.petnaest;
    }
    
    public void setPetnaest(String petnaest) {
        this.petnaest = petnaest;
    }

    
    @Column(name="sajamcol", length=45)
    public String getSajamcol() {
        return this.sajamcol;
    }
    
    public void setSajamcol(String sajamcol) {
        this.sajamcol = sajamcol;
    }




}


