package beans;
// Generated Feb 10, 2019 3:24:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Telefon generated by hbm2java
 */
@Entity
@Table(name="telefon"
    ,catalog="job_fair"
)
public class Telefon  implements java.io.Serializable {


     private int idTel;
     private Biografija biografija;
     private String broj;

    public Telefon() {
    }

    public Telefon(Biografija biografija, String broj) {
       this.biografija = biografija;
       this.broj = broj;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="biografija"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id_tel", unique=true, nullable=false)
    public int getIdTel() {
        return this.idTel;
    }
    
    public void setIdTel(int idTel) {
        this.idTel = idTel;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Biografija getBiografija() {
        return this.biografija;
    }
    
    public void setBiografija(Biografija biografija) {
        this.biografija = biografija;
    }

    
    @Column(name="broj", nullable=false, length=45)
    public String getBroj() {
        return this.broj;
    }
    
    public void setBroj(String broj) {
        this.broj = broj;
    }




}


