package beans;
// Generated Feb 12, 2019 2:08:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WebSites generated by hbm2java
 */
@Entity
@Table(name="webSites"
    ,catalog="job_fair"
)
public class WebSites  implements java.io.Serializable {


     private Integer idwebSites;
     private Biografija biografija;
     private String web;

    public WebSites() {
    }

    public WebSites(Biografija biografija, String web) {
       this.biografija = biografija;
       this.web = web;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idwebSites", unique=true, nullable=false)
    public Integer getIdwebSites() {
        return this.idwebSites;
    }
    
    public void setIdwebSites(Integer idwebSites) {
        this.idwebSites = idwebSites;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcv", nullable=false)
    public Biografija getBiografija() {
        return this.biografija;
    }
    
    public void setBiografija(Biografija biografija) {
        this.biografija = biografija;
    }

    
    @Column(name="web", nullable=false, length=45)
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }




}


