package beans;
// Generated Feb 10, 2019 3:24:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Zaposlenje generated by hbm2java
 */
@Entity
@Table(name="zaposlenje"
    ,catalog="job_fair"
)
public class Zaposlenje  implements java.io.Serializable {


     private int id;
     private Biografija biografija;
     private Date dateOd;
     private Date dateDo;
     private int onGoing;
     private String pozicija;
     private String firma;

    public Zaposlenje() {
    }

    public Zaposlenje(Biografija biografija, Date dateOd, Date dateDo, int onGoing, String pozicija, String firma) {
       this.biografija = biografija;
       this.dateOd = dateOd;
       this.dateDo = dateDo;
       this.onGoing = onGoing;
       this.pozicija = pozicija;
       this.firma = firma;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="biografija"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Biografija getBiografija() {
        return this.biografija;
    }
    
    public void setBiografija(Biografija biografija) {
        this.biografija = biografija;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_od", nullable=false, length=10)
    public Date getDateOd() {
        return this.dateOd;
    }
    
    public void setDateOd(Date dateOd) {
        this.dateOd = dateOd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_do", nullable=false, length=10)
    public Date getDateDo() {
        return this.dateDo;
    }
    
    public void setDateDo(Date dateDo) {
        this.dateDo = dateDo;
    }

    
    @Column(name="on_going", nullable=false)
    public int getOnGoing() {
        return this.onGoing;
    }
    
    public void setOnGoing(int onGoing) {
        this.onGoing = onGoing;
    }

    
    @Column(name="pozicija", nullable=false, length=45)
    public String getPozicija() {
        return this.pozicija;
    }
    
    public void setPozicija(String pozicija) {
        this.pozicija = pozicija;
    }

    
    @Column(name="firma", nullable=false, length=45)
    public String getFirma() {
        return this.firma;
    }
    
    public void setFirma(String firma) {
        this.firma = firma;
    }




}


