package beans;
// Generated Feb 12, 2019 2:08:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Zaposlenje generated by hbm2java
 */
@Entity
@Table(name="zaposlenje"
    ,catalog="job_fair"
)
public class Zaposlenje  implements java.io.Serializable {


     private Integer idzaposlenje;
     private Biografija biografija;
     private Date dateOd;
     private Date dateDo;
     private String onGoing;
     private String pozicija;
     private String firma;

    public Zaposlenje() {
    }

    public Zaposlenje(Biografija biografija, Date dateOd, Date dateDo, String onGoing, String pozicija, String firma) {
       this.biografija = biografija;
       this.dateOd = dateOd;
       this.dateDo = dateDo;
       this.onGoing = onGoing;
       this.pozicija = pozicija;
       this.firma = firma;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idzaposlenje", unique=true, nullable=false)
    public Integer getIdzaposlenje() {
        return this.idzaposlenje;
    }
    
    public void setIdzaposlenje(Integer idzaposlenje) {
        this.idzaposlenje = idzaposlenje;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idbio", nullable=false)
    public Biografija getBiografija() {
        return this.biografija;
    }
    
    public void setBiografija(Biografija biografija) {
        this.biografija = biografija;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_od", nullable=false, length=10)
    public Date getDateOd() {
        return this.dateOd;
    }
    
    public void setDateOd(Date dateOd) {
        this.dateOd = dateOd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_do", nullable=false, length=10)
    public Date getDateDo() {
        return this.dateDo;
    }
    
    public void setDateDo(Date dateDo) {
        this.dateDo = dateDo;
    }

    
    @Column(name="on_going", nullable=false, length=45)
    public String getOnGoing() {
        return this.onGoing;
    }
    
    public void setOnGoing(String onGoing) {
        this.onGoing = onGoing;
    }

    
    @Column(name="pozicija", nullable=false, length=45)
    public String getPozicija() {
        return this.pozicija;
    }
    
    public void setPozicija(String pozicija) {
        this.pozicija = pozicija;
    }

    
    @Column(name="firma", nullable=false, length=45)
    public String getFirma() {
        return this.firma;
    }
    
    public void setFirma(String firma) {
        this.firma = firma;
    }




}


